package com.dooapp.gaedo.blueprints.strategies;

import java.util.Collection;
import java.util.Map;

import javax.persistence.CascadeType;

import com.dooapp.gaedo.blueprints.AbstractBluePrintsBackedFinderService;
import com.dooapp.gaedo.properties.Property;

/**
 * Interface adapting some specific behaviours of a graph service. This interface should typically allow one to choose bvetween bean based graph mapping and graph based bean mapping (in which case
 * one could use PropertyBag and associated classes).
 * @author ndx
 *
 */
public interface GraphMappingStrategy<DataType> {
	/**
	 * Delegation method allowing one to get the map linking properties to cascade types
	 * @param object
	 * @return a map associating each property to its cascade type (useful for persistence operation, but will have to be slightly updated for load operations).
	 */
	public Map<Property, Collection<CascadeType>> getContainedProperties(DataType object);
	
	
	public void assignId(final DataType value, final Object... id);

	public void generateValidIdFor(AbstractBluePrintsBackedFinderService<?, DataType, ?> service, DataType toCreate);
	
	/**
	 * Get an id string for the given object
	 * @param object
	 * @return
	 */
	public String getIdString(DataType object);

	/**
	 * Transform given object into a string that could be an object id (provided that object id was generated by {@link #getIdString(Object)})
	 * @param object
	 * @return
	 */
	public String getAsId(Object object);


	public Collection<Property> getIdProperties();
	
	public boolean isIdGenerationRequired();
}
